import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FIG = path.join(ROOT, "docs", "figures");
const IDS = [
  "hook-gpu-hours",
  "cost-ladder",
  "drivers",
  "lithography",
  "accuracy",
  "flaky-sites",
  "agents-report-card",
];

await import(path.join(FIG, "index.js"));
for (const id of IDS) await import(path.join(FIG, `${id}.js`));
const F = globalThis.GPUStackFigures;

test("the figures API is registered", () => {
  assert.equal(typeof F.mount, "function");
  assert.equal(typeof F.define, "function");
  assert.deepEqual(F.ids, IDS);
});

for (const id of IDS) {
  test(`figure ${id} registers a title, a text alternative and a builder`, () => {
    const def = F.defs[id];
    assert.ok(def, `${id} not registered`);
    assert.equal(typeof def.build, "function");
    assert.ok(def.title && def.title.length < 40, "short title");
    assert.ok(def.label && def.label.length > 20, "aria-label");
    assert.ok(def.summary && def.summary.length > 60, "summary for the hidden figcaption");
  });

  test(`figure ${id} follows the voice rules and stays small`, async () => {
    const src = await fs.readFile(path.join(FIG, `${id}.js`), "utf8");
    assert.ok(!src.includes("—"), "no em dash");
    assert.ok(src.length < 25 * 1024, `${id}.js is ${src.length} bytes`);
    const def = F.defs[id];
    for (const text of [def.title, def.label, def.summary]) {
      assert.ok(!text.includes("!"), "no exclamation point");
      assert.ok(!text.includes("—"), "no em dash");
    }
  });
}

test("the GPU-hours figure shows no dollar figures", async () => {
  const src = await fs.readFile(path.join(FIG, "hook-gpu-hours.js"), "utf8");
  assert.ok(!src.includes("$"), "no dollar amounts in the parallelism figure");
});

test("why-so-many-gpus is an alias of the GPU-hours figure", async () => {
  const src = await fs.readFile(path.join(FIG, "index.js"), "utf8");
  assert.match(src, /"why-so-many-gpus": "hook-gpu-hours"/);
});

test("published-runs.json has 27 tier A rows with citations", async () => {
  const file = path.join(ROOT, "docs", "data", "published-runs.json");
  let raw;
  try {
    raw = await fs.readFile(file, "utf8");
  } catch {
    return; // generated by scripts/build_accuracy_figure_data.py; absent is allowed
  }
  const doc = JSON.parse(raw);
  assert.equal(doc.rows.length, 27);
  for (const row of doc.rows) {
    assert.equal(row.tier, "A", row.id);
    assert.ok(row.reported_per_trillion_tokens > 0, row.id);
    assert.ok(row.predicted_rule_40pct_mfu_per_trillion_tokens > 0, row.id);
    assert.ok(row.predicted_graph_per_trillion_tokens > 0, row.id);
    const cites = Object.values(row.citations).flat();
    assert.ok(cites.length >= 3, `${row.id} has citations`);
    for (const c of cites) {
      assert.ok(c.source && c.where, `${row.id} citation is complete`);
    }
  }
  assert.ok(Math.abs(doc.median_error.rule_of_thumb - 0.22) < 0.01);
  assert.ok(Math.abs(doc.median_error.graph - 0.22) < 0.01);
});

test("the built-in copy of the accuracy rows matches published-runs.json", async () => {
  const file = path.join(ROOT, "docs", "data", "published-runs.json");
  let doc;
  try {
    doc = JSON.parse(await fs.readFile(file, "utf8"));
  } catch {
    return;
  }
  const src = await fs.readFile(path.join(FIG, "accuracy.js"), "utf8");
  const match = src.match(/var FALLBACK = (\[\[.*\]\]);/);
  assert.ok(match, "fallback present");
  const fallback = JSON.parse(match[1]);
  assert.equal(fallback.length, doc.rows.length);
  fallback.forEach((r, i) => {
    const row = doc.rows[i];
    assert.equal(r[1], row.reported_per_trillion_tokens);
    assert.equal(r[2], row.predicted_rule_40pct_mfu_per_trillion_tokens);
    assert.equal(r[3], row.predicted_graph_per_trillion_tokens);
  });
});
