"""
tests/test_lithography_medium_composition_unit_checks.py
========================================================

The imaging medium composition equations should keep unit checks enabled.
"""

from gpu_stack import Registry


def test_lithography_medium_formula_unit_equations_have_unit_checks():
    checked_names = {
        "physical.ineq.lithography_medium_component_a_stoichiometric_count_at_least_one",
        "physical.ineq.lithography_medium_component_b_stoichiometric_count_at_least_one",
        "physical.eq.lithography_medium_component_a_valence_up_quark_count_from_zn",
        "physical.eq.lithography_medium_component_a_valence_down_quark_count_from_zn",
        "physical.eq.lithography_medium_component_b_valence_up_quark_count_from_zn",
        "physical.eq.lithography_medium_component_b_valence_down_quark_count_from_zn",
        "physical.ineq.lithography_medium_component_a_proton_count_positive",
        "physical.ineq.lithography_medium_component_b_proton_count_positive",
        "physical.eq.lithography_medium_component_a_atomic_number",
        "physical.eq.lithography_medium_component_b_atomic_number",
        "physical.eq.lithography_medium_component_a_isotope_mass_number",
        "physical.eq.lithography_medium_component_b_isotope_mass_number",
        "physical.eq.lithography_medium_component_binding_volume_coefficient_from_shared_nuclear_calibration",
        "physical.eq.lithography_medium_component_binding_surface_coefficient_from_shared_nuclear_calibration",
        "physical.eq.lithography_medium_component_binding_coulomb_coefficient_from_shared_nuclear_calibration",
        "physical.eq.lithography_medium_component_binding_asymmetry_coefficient_from_shared_nuclear_calibration",
        "physical.eq.lithography_medium_component_nuclear_pairing_gap_reference_energy_from_shared_nuclear_calibration",
        "physical.eq.lithography_medium_component_nuclear_radius_coefficient",
        "physical.eq.lithography_medium_component_nuclear_saturation_number_density",
        "physical.eq.lithography_medium_component_nuclear_bulk_binding_energy_density",
        "physical.eq.lithography_medium_component_nuclear_surface_tension",
        "physical.eq.lithography_medium_component_nuclear_symmetry_energy_density",
        "physical.eq.lithography_medium_component_a_neutron_excess",
        "physical.eq.lithography_medium_component_b_neutron_excess",
        "physical.eq.lithography_medium_component_a_pairing_sign",
        "physical.eq.lithography_medium_component_b_pairing_sign",
        "physical.eq.lithography_medium_component_a_pairing_reference_mass_number",
        "physical.eq.lithography_medium_component_b_pairing_reference_mass_number",
        "physical.eq.lithography_medium_component_a_binding_pairing_coefficient",
        "physical.eq.lithography_medium_component_b_binding_pairing_coefficient",
        "physical.eq.lithography_medium_component_a_binding_volume_term",
        "physical.eq.lithography_medium_component_b_binding_volume_term",
        "physical.eq.lithography_medium_component_a_binding_surface_term",
        "physical.eq.lithography_medium_component_b_binding_surface_term",
        "physical.eq.lithography_medium_component_a_binding_coulomb_term",
        "physical.eq.lithography_medium_component_b_binding_coulomb_term",
        "physical.eq.lithography_medium_component_a_binding_asymmetry_term",
        "physical.eq.lithography_medium_component_b_binding_asymmetry_term",
        "physical.eq.lithography_medium_component_a_binding_pairing_term",
        "physical.eq.lithography_medium_component_b_binding_pairing_term",
        "physical.eq.lithography_medium_component_a_binding_energy",
        "physical.eq.lithography_medium_component_b_binding_energy",
        "physical.ineq.lithography_medium_formula_unit_intercomponent_charge_transfer_at_most_component_a_electron_inventory",
        "physical.ineq.lithography_medium_formula_unit_intercomponent_charge_transfer_at_most_component_b_electron_inventory",
        "physical.eq.lithography_medium_intercomponent_charge_unit_from_formula_unit_charge_transfer",
        "physical.eq.lithography_medium_component_a_effective_intercomponent_charge_number",
        "physical.eq.lithography_medium_component_b_effective_intercomponent_charge_number",
        "physical.eq.lithography_medium_formula_unit_intercomponent_pair_count",
        "physical.eq.lithography_medium_component_a_effective_intercomponent_radius",
        "physical.eq.lithography_medium_component_b_effective_intercomponent_radius",
        "physical.eq.lithography_medium_intercomponent_gap_from_radius_fraction",
        "physical.eq.lithography_medium_intercomponent_effective_separation",
        "physical.eq.lithography_medium_formula_unit_intercomponent_binding_energy",
        "physical.eq.lithography_medium_formula_unit_proton_count",
        "physical.eq.lithography_medium_formula_unit_neutron_count",
        "physical.eq.lithography_medium_formula_unit_binding_energy",
        "physical.eq.lithography_medium_formula_unit_electron_count",
        "physical.eq.lithography_medium_formula_unit_rest_mass",
        "physical.eq.lithography_medium_molar_mass",
        "physical.eq.lithography_medium_particle_mass",
        "physical.ineq.lithography_medium_formula_unit_packing_length_scale_factor_at_least_unity",
        "physical.eq.lithography_medium_formula_unit_packing_length_from_intercomponent_separation_scale",
        "physical.ineq.lithography_medium_formula_unit_packing_fill_factor_at_most_unity",
        "physical.eq.lithography_medium_formula_unit_packing_volume",
        "physical.eq.lithography_medium_mass_density_from_packing",
        "physical.eq.lithography_medium_number_density_from_mass",
        "physical.eq.lithography_medium_polarizable_electron_fraction_from_count",
        "physical.ineq.lithography_medium_polarizable_electron_count_within_formula_unit",
        "physical.eq.lithography_medium_oscillator_sum_rule_fraction_from_count",
        "physical.ineq.lithography_medium_dominant_oscillator_electron_count_within_polarizable_count",
        "physical.eq.lithography_medium_resonance_to_source_frequency_ratio_from_energy",
        "physical.ineq.lithography_medium_resonance_energy_above_source_photon_energy",
        "physical.eq.lithography_medium_resonance_angular_frequency_from_source_ratio",
        "physical.eq.lithography_medium_oscillator_strength_from_formula_electrons",
        "physical.eq.lithography_medium_electric_polarizability",
        "physical.eq.lithography_medium_intercomponent_lorentz_lorenz_factor",
        "physical.eq.lithography_medium_intercomponent_relative_permittivity_from_local_lorentz_lorenz",
    }
    for name in checked_names:
        assert getattr(Registry.equations[name], "_check_units_flag", False), name
