"""Research artifacts for measured validation of the GPUSTACK world model."""

from .backends import (
    BackendCapability,
    BackendRoutingError,
    CompositeWorldModel,
    PredictionEstimate,
    PredictionRequest,
    WorldModelBackend,
)
from .benchmarks import (
    BenchmarkAggregation,
    BenchmarkCase,
    BenchmarkDefinition,
    BenchmarkReport,
    CalibrationMeanBackend,
    ConfigurationAggregate,
    run_benchmark,
)
from .e001 import (
    AdaptiveCadencePolicy,
    AdaptiveConsistencyPolicy,
    E001Comparison,
    E001MechanicsMetrics,
    E001PolicyKind,
    E001Run,
    E001Scenario,
    E001SyncCycle,
    E001_ENGINE_ID,
    E001_PROTOCOL,
    E001_RESULT_SCHEMA,
    LearningProgressCalibration,
    LearningProgressPrior,
    SiteOutage,
    run_e001,
    e001_engine_source_hash,
)
from .e001_recovery_v2 import (
    E001_PARENT_BASELINE_OBLIGATION_IDS,
    E001_RECOVERY_V2_BASELINE_POLICY_IDS,
    E001_RECOVERY_V2_CANDIDATE_POLICY_ID,
    E001_RECOVERY_V2_POLICY_IDS,
    E001_RECOVERY_V2_POLICY_ROLES,
    E001_RECOVERY_V2_PROTOCOL,
)
from .e001_recovery_artifact import (
    E001_RECOVERY_RESULT_SCHEMA,
    build_e001_recovery_result,
    e001_recovery_result_json,
)
from .e001_recovery_runner import (
    E001RecoveryExecution,
    E001RecoveryScenario,
    run_e001_recovery_v2,
)
from .e001_learning_calibration import (
    ADAPTIVE_POLICY as E001_LC1_ADAPTIVE_POLICY,
    ENGINE_ID as E001_LC1_ENGINE_ID,
    FIXED_POLICY as E001_LC1_FIXED_POLICY,
    SCHEMA as E001_LC1_SCHEMA,
    SYNC_POLICY as E001_LC1_SYNC_POLICY,
    run_e001_learning_calibration,
)
from .e001_lc2_quality_target import (
    ENGINE_ID as E001_LC2_ENGINE_ID,
    SCHEMA as E001_LC2_SCHEMA,
    run_e001_lc2_quality_target,
)
from .e001_lc3_equal_work import (
    ENGINE_ID as E001_LC3_ENGINE_ID,
    SCHEMA as E001_LC3_SCHEMA,
    run_e001_lc3_equal_work,
)
from .e001_semantic_consistency import (
    ENGINE_ID as E001_SC1_ENGINE_ID,
    SCHEMA as E001_SC1_SCHEMA,
    run_e001_semantic_consistency,
)

from .evaluation import (
    DecisionRegret,
    IntervalCoverage,
    IntervalCoverageLevel,
    IntervalCoveragePanel,
    StratifiedIntervalCoverage,
    KendallTauB,
    Prediction,
    PredictionInterval,
    PredictionRecord,
    RankingCorrelation,
    ResidualAttribution,
    ResidualContribution,
    ResidualMetrics,
    attribute_residual,
    compute_decision_regret,
    configuration_ranking_correlation,
    configuration_kendall_tau_b,
    decision_regret,
    evaluate_prediction,
    evaluate_predictions,
    interval_coverage,
    stratified_interval_coverage,
    kendall_tau_b,
    ranking_correlation,
    summarize_interval_coverage,
    summarize_interval_coverage_stratified,
)
from .observations import (
    CalibrationEvaluationSplit,
    CalibrationSplit,
    DatasetSplit,
    EvaluationSplit,
    JSONPrimitive,
    JSONValue,
    Measurement,
    MeasurementUncertainty,
    MeasuredValue,
    Observation,
    ObservationSplit,
    Provenance,
)
from .observatory import build_e001_observatory_artifact, e001_observatory_json
from .observatory_recovery import (
    E001_RECOVERY_OBSERVATORY_SCHEMA,
    build_e001_recovery_observatory_artifact,
    e001_recovery_observatory_json,
)
from .observatory_learning import (
    E001_LEARNING_OBSERVATORY_SCHEMA,
    build_e001_learning_observatory_artifact,
    project_e001_learning_result_file,
)
from .observatory_equal_work import (
    SCHEMA as E001_EQUAL_WORK_OBSERVATORY_SCHEMA,
    build_e001_equal_work_observatory_artifact,
    project_e001_equal_work_result_file,
)
from .observatory_semantic_consistency import (
    RAW_SCHEMA as E001_SC1_RAW_OBSERVATORY_SCHEMA,
    SCHEMA as E001_SC1_OBSERVATORY_SCHEMA,
    build_e001_semantic_consistency_observatory_artifact,
    build_e001_semantic_consistency_raw_artifact,
)
from .e002_checkpoint_power import (
    ENGINE_ID as E002_CHECKPOINT_POWER_ENGINE_ID,
    SCHEMA as E002_CHECKPOINT_POWER_SCHEMA,
    run_e002_checkpoint_power,
)
from .observatory_checkpoint_power import (
    RAW_SCHEMA as E002_CHECKPOINT_POWER_RAW_OBSERVATORY_SCHEMA,
    SCHEMA as E002_CHECKPOINT_POWER_OBSERVATORY_SCHEMA,
    build_e002_checkpoint_power_observatory_artifact,
    build_e002_checkpoint_power_raw_artifact,
    project_e002_checkpoint_power_result_file,
)
from .e002_cumulative_energy import (
    ENGINE_ID as E002_CUMULATIVE_ENERGY_ENGINE_ID,
    SCHEMA as E002_CUMULATIVE_ENERGY_SCHEMA,
    run_e002_cumulative_energy,
)
from .observatory_checkpoint_energy import (
    RAW_SCHEMA as E002_CUMULATIVE_ENERGY_RAW_OBSERVATORY_SCHEMA,
    SCHEMA as E002_CUMULATIVE_ENERGY_OBSERVATORY_SCHEMA,
    build_e002_checkpoint_energy_observatory_artifact,
    build_e002_checkpoint_energy_raw_artifact,
    project_e002_checkpoint_energy_result_file,
)
from .recovery import (
    CheckpointLedger,
    CompletedCheckpoint,
    EvidenceBasis,
    EvidenceBoundary,
    FailureInterval,
    FailureObservation,
    FailureStatus,
    FailureTrace,
    RecoveryPlan,
    RecoveryPlanningError,
    RecoveryRequest,
    SiteWorkAttempt,
    WorkAttemptKind,
    WorkAttemptOutcome,
    WorkLedger,
    evaluate_work_attempt,
    plan_recovery,
)
from .multisite import (
    ConfigurationIntervention,
    DatacenterMetrics,
    DatacenterResult,
    DatacenterTrace,
    Intervention,
    InterventionRecord,
    MembershipIntervention,
    MigrationIntervention,
    ParallelismConfig,
    ParallelismIntervention,
    Policy,
    PowerCapIntervention,
    ResourceUtilization,
    Site,
    SyncCadence,
    SyncCadenceIntervention,
    VisibleDatacenterState,
    VisibleLinkState,
    VisibleSiteState,
    VirtualDatacenter,
    WANLink,
)
from .protocols import (
    ComparisonOperator,
    EvidenceRequirementResult,
    EvidenceRequirementSpec,
    EvidenceRequirementStatus,
    EXPERIMENT_RUN_SCHEMA,
    ExperimentProtocol,
    ExperimentRunArtifact,
    ExperimentStage,
    FalsifierResult,
    FalsifierSpec,
    MetricSpec,
)
from .programs import (
    E002_PROTOCOL,
    E003_PROTOCOL,
    E004_PROTOCOL,
    E005_PROTOCOL,
    E006_PROTOCOL,
    EXPERIMENT_PROTOCOLS,
    protocol_catalog,
    protocol_for,
)
from .symbolic_backend import SymbolicPredictionError, SymbolicResolverBackend
from .temporal import (
    EventKind,
    EventRecord,
    EventTimeline,
    Resource,
    ResourceDemand,
    ResourceUsageSnapshot,
    TemporalEvent,
    TimelineResult,
    TimelineTrace,
    VisibleStateSnapshot,
    duration_ns_for_rate,
    seconds_to_ns,
)


__all__ = [
    "BackendCapability",
    "BackendRoutingError",
    "CompositeWorldModel",
    "PredictionEstimate",
    "PredictionRequest",
    "WorldModelBackend",
    "BenchmarkAggregation",
    "BenchmarkCase",
    "BenchmarkDefinition",
    "BenchmarkReport",
    "CalibrationMeanBackend",
    "ConfigurationAggregate",
    "run_benchmark",
    "JSONPrimitive",
    "JSONValue",
    "MeasurementUncertainty",
    "MeasuredValue",
    "Measurement",
    "Provenance",
    "Observation",
    "CalibrationSplit",
    "EvaluationSplit",
    "CalibrationEvaluationSplit",
    "ObservationSplit",
    "DatasetSplit",
    "PredictionInterval",
    "PredictionRecord",
    "Prediction",
    "ResidualMetrics",
    "evaluate_prediction",
    "evaluate_predictions",
    "IntervalCoverage",
    "IntervalCoverageLevel",
    "IntervalCoveragePanel",
    "StratifiedIntervalCoverage",
    "summarize_interval_coverage",
    "summarize_interval_coverage_stratified",
    "interval_coverage",
    "stratified_interval_coverage",
    "RankingCorrelation",
    "KendallTauB",
    "configuration_ranking_correlation",
    "ranking_correlation",
    "configuration_kendall_tau_b",
    "kendall_tau_b",
    "DecisionRegret",
    "decision_regret",
    "compute_decision_regret",
    "ResidualContribution",
    "ResidualAttribution",
    "attribute_residual",
    "ComparisonOperator",
    "EvidenceRequirementResult",
    "EvidenceRequirementSpec",
    "EvidenceRequirementStatus",
    "EXPERIMENT_RUN_SCHEMA",
    "ExperimentProtocol",
    "ExperimentRunArtifact",
    "ExperimentStage",
    "FalsifierResult",
    "FalsifierSpec",
    "MetricSpec",
    "E002_PROTOCOL",
    "E003_PROTOCOL",
    "E004_PROTOCOL",
    "E005_PROTOCOL",
    "E006_PROTOCOL",
    "EXPERIMENT_PROTOCOLS",
    "protocol_catalog",
    "protocol_for",
    "SymbolicPredictionError",
    "SymbolicResolverBackend",
    "EventKind",
    "EventRecord",
    "EventTimeline",
    "Resource",
    "ResourceDemand",
    "ResourceUsageSnapshot",
    "TemporalEvent",
    "TimelineResult",
    "TimelineTrace",
    "VisibleStateSnapshot",
    "duration_ns_for_rate",
    "seconds_to_ns",
    "ConfigurationIntervention",
    "DatacenterMetrics",
    "DatacenterResult",
    "DatacenterTrace",
    "Intervention",
    "InterventionRecord",
    "MembershipIntervention",
    "MigrationIntervention",
    "ParallelismConfig",
    "ParallelismIntervention",
    "Policy",
    "PowerCapIntervention",
    "ResourceUtilization",
    "Site",
    "SyncCadence",
    "SyncCadenceIntervention",
    "VisibleDatacenterState",
    "VisibleLinkState",
    "VisibleSiteState",
    "VirtualDatacenter",
    "WANLink",
    "AdaptiveCadencePolicy",
    "AdaptiveConsistencyPolicy",
    "E001Comparison",
    "E001MechanicsMetrics",
    "E001PolicyKind",
    "E001Run",
    "E001Scenario",
    "E001SyncCycle",
    "E001_ENGINE_ID",
    "E001_PROTOCOL",
    "E001_RESULT_SCHEMA",
    "E001_PARENT_BASELINE_OBLIGATION_IDS",
    "E001_RECOVERY_V2_BASELINE_POLICY_IDS",
    "E001_RECOVERY_V2_CANDIDATE_POLICY_ID",
    "E001_RECOVERY_V2_POLICY_IDS",
    "E001_RECOVERY_V2_POLICY_ROLES",
    "E001_RECOVERY_V2_PROTOCOL",
    "E001_RECOVERY_RESULT_SCHEMA",
    "E001RecoveryExecution",
    "E001RecoveryScenario",
    "run_e001_recovery_v2",
    "build_e001_recovery_result",
    "e001_recovery_result_json",
    "E001_LC1_ADAPTIVE_POLICY",
    "E001_LC1_ENGINE_ID",
    "E001_LC1_FIXED_POLICY",
    "E001_LC1_SCHEMA",
    "E001_LC1_SYNC_POLICY",
    "run_e001_learning_calibration",
    "E001_LC2_ENGINE_ID",
    "E001_LC2_SCHEMA",
    "run_e001_lc2_quality_target",
    "E001_LC3_ENGINE_ID",
    "E001_LC3_SCHEMA",
    "run_e001_lc3_equal_work",
    "E001_SC1_ENGINE_ID",
    "E001_SC1_SCHEMA",
    "run_e001_semantic_consistency",
    "LearningProgressCalibration",
    "LearningProgressPrior",
    "SiteOutage",
    "run_e001",
    "e001_engine_source_hash",
    "build_e001_observatory_artifact",
    "e001_observatory_json",
    "E001_RECOVERY_OBSERVATORY_SCHEMA",
    "build_e001_recovery_observatory_artifact",
    "e001_recovery_observatory_json",
    "E001_LEARNING_OBSERVATORY_SCHEMA",
    "build_e001_learning_observatory_artifact",
    "project_e001_learning_result_file",
    "E001_EQUAL_WORK_OBSERVATORY_SCHEMA",
    "build_e001_equal_work_observatory_artifact",
    "E001_SC1_OBSERVATORY_SCHEMA",
    "E001_SC1_RAW_OBSERVATORY_SCHEMA",
    "build_e001_semantic_consistency_observatory_artifact",
    "build_e001_semantic_consistency_raw_artifact",
    "E002_CHECKPOINT_POWER_ENGINE_ID",
    "E002_CHECKPOINT_POWER_SCHEMA",
    "run_e002_checkpoint_power",
    "E002_CHECKPOINT_POWER_OBSERVATORY_SCHEMA",
    "E002_CHECKPOINT_POWER_RAW_OBSERVATORY_SCHEMA",
    "build_e002_checkpoint_power_observatory_artifact",
    "build_e002_checkpoint_power_raw_artifact",
    "project_e002_checkpoint_power_result_file",
    "E002_CUMULATIVE_ENERGY_ENGINE_ID",
    "E002_CUMULATIVE_ENERGY_SCHEMA",
    "run_e002_cumulative_energy",
    "E002_CUMULATIVE_ENERGY_OBSERVATORY_SCHEMA",
    "E002_CUMULATIVE_ENERGY_RAW_OBSERVATORY_SCHEMA",
    "build_e002_checkpoint_energy_observatory_artifact",
    "build_e002_checkpoint_energy_raw_artifact",
    "project_e002_checkpoint_energy_result_file",
    "project_e001_equal_work_result_file",
    "CheckpointLedger",
    "CompletedCheckpoint",
    "EvidenceBasis",
    "EvidenceBoundary",
    "FailureInterval",
    "FailureObservation",
    "FailureStatus",
    "FailureTrace",
    "RecoveryPlan",
    "RecoveryPlanningError",
    "RecoveryRequest",
    "SiteWorkAttempt",
    "WorkAttemptKind",
    "WorkAttemptOutcome",
    "WorkLedger",
    "evaluate_work_attempt",
    "plan_recovery",
]
